import { Part } from '@google/genai';

/**
 * @type ActiveTab
 * @description Represents the currently active tab in the UI.
 * @description Repräsentiert den aktuell aktiven Tab in der Benutzeroberfläche.
 */
export type ActiveTab = 'dashboard' | 'documents' | 'analysis' | 'generation' | 'library' | 'reports' | 'kpis' | 'agents' | 'strategy' | 'dispatch' | 'chronology' | 'entities' | 'knowledge' | 'contradictions' | 'settings' | 'legal' | 'un-submissions' | 'ethics' | 'audit' | 'graph';

/**
 * @type AgentCapability
 * @description Defines the specific capabilities an AI agent can have.
 * @description Definiert die spezifischen Fähigkeiten, die ein KI-Agent besitzen kann.
 */
export type AgentCapability =
  | 'workload_calculation'
  | 'cost_analysis'
  | 'document_analysis'
  | 'information_extraction'
  | 'document_linking'
  | 'un_submission_assistance'
  | 'legal_analysis'
  | 'contradiction_detection'
  | 'compliance_check'
  | 'risk_assessment'
  | 'case_analysis'
  | 'report_generation'
  | 'attrition_analysis'
  | 'content_creation'
  | 'official_documents'
  | 'un_submission_finalization'
  | 'strategy_development'
  | 'kpi_suggestion'
  | 'task_suggestion'
  | 'research'
  | 'public_communication';

// --- Database Schema Types ---

/**
 * @interface ChainOfCustodyEvent
 * @description Represents a single event in a document's chain of custody, for tracking and auditing.
 * @description Stellt ein einzelnes Ereignis in der Chain of Custody eines Dokuments dar, zur Nachverfolgung und Prüfung.
 * @property {string} id - Unique identifier for the event. / Eindeutiger Bezeichner für das Ereignis.
 * @property {string} timestamp - The ISO 8601 timestamp of the event. / Der ISO 8601 Zeitstempel des Ereignisses.
 * @property {string} action - The action performed (e.g., 'created', 'hashed'). / Die durchgeführte Aktion (z.B. 'erstellt', 'gehasht').
 * @property {string} contentHash - The SHA-256 hash of the document content at the time of the event. / Der SHA-256 Hash des Dokumenteninhalts zum Zeitpunkt des Ereignisses.
 */
export interface ChainOfCustodyEvent {
    id: string;
    timestamp: string;
    action: string;
    contentHash: string;
}

/**
 * @interface Document
 * @description Represents a single document uploaded to the system.
 * @description Stellt ein einzelnes, in das System hochgeladenes Dokument dar.
 * @property {string} id - Unique identifier for the document. / Eindeutiger Bezeichner für das Dokument.
 * @property {string} name - The original filename of the document. / Der ursprüngliche Dateiname des Dokuments.
 * @property {string} type - The MIME type of the document. / Der MIME-Typ des Dokuments.
 * @property {string} content - The extracted text content of the document. / Der extrahierte Textinhalt des Dokuments.
 * @property {number} size - The size of the document in bytes. / Die Größe des Dokuments in Bytes.
 * @property {string} uploadDate - The ISO 8601 timestamp of when the document was uploaded. / Der ISO 8601 Zeitstempel des Hochladens.
 * @property {'unclassified' | 'classifying' | 'classified' | 'failed'} classificationStatus - The current classification status. / Der aktuelle Klassifizierungsstatus.
 * @property {string[]} tags - A list of tags associated with the document. / Eine Liste von Tags, die mit dem Dokument verknüpft sind.
 * @property {string} workCategory - The category of work this document belongs to. / Die Arbeitskategorie, zu der dieses Dokument gehört.
 * @property {ChainOfCustodyEvent[]} chainOfCustody - The chain of custody history for this document. / Die Historie der Chain of Custody für dieses Dokument.
 */
export interface Document {
    id: string;
    name: string;
    type: string;
    content: string;
    size: number;
    uploadDate: string;
    classificationStatus: 'unclassified' | 'classifying' | 'classified' | 'failed';
    tags: string[];
    workCategory: string;
    chainOfCustody: ChainOfCustodyEvent[];
}

/**
 * @interface GeneratedDocument
 * @description Represents a document that has been generated by an AI agent.
 * @description Stellt ein Dokument dar, das von einem KI-Agenten generiert wurde.
 * @property {string} id - Unique identifier for the generated document. / Eindeutiger Bezeichner für das generierte Dokument.
 * @property {string} title - The title of the document. / Der Titel des Dokuments.
 * @property {string} content - The main content of the document. / Der Hauptinhalt des Dokuments.
 * @property {string} createdAt - The ISO 8601 timestamp of creation. / Der ISO 8601 Zeitstempel der Erstellung.
 * @property {'draft' | 'review' | 'final'} status - The current status of the document. / Der aktuelle Status des Dokuments.
 * @property {number} version - The version number of the document. / Die Versionsnummer des Dokuments.
 */
export interface GeneratedDocument {
    id: string;
    title: string;
    content: string;
    createdAt: string;
    status: 'draft' | 'review' | 'final';
    version: number;
}

/**
 * @interface Entity
 * @description Represents a recognized entity (person, organization, etc.) within the case.
 * @description Stellt eine erkannte Entität (Person, Organisation, etc.) innerhalb des Falles dar.
 * @property {string} id - Unique identifier for the entity. / Eindeutiger Bezeichner für die Entität.
 * @property {string} name - The name of the entity. / Der Name der Entität.
 * @property {'Person' | 'Organisation' | 'Standort' | 'Unbekannt'} type - The type of the entity. / Der Typ der Entität.
 * @property {string} description - A brief description of the entity. / Eine kurze Beschreibung der Entität.
 */
export interface Entity {
    id: string;
    name: string;
    type: 'Person' | 'Organisation' | 'Standort' | 'Unbekannt';
    description: string;
}

/**
 * @interface KnowledgeItem
 * @description Represents a single piece of structured knowledge extracted from documents.
 * @description Stellt ein einzelnes, aus Dokumenten extrahiertes, strukturiertes Wissenselement dar.
 * @property {string} id - Unique identifier for the knowledge item. / Eindeutiger Bezeichner für das Wissenselement.
 * @property {string} title - A concise title for the knowledge item. / Ein prägnanter Titel für das Wissenselement.
 * @property {string} summary - A summary of the knowledge. / Eine Zusammenfassung des Wissens.
 * @property {string} category - The category of the knowledge. / Die Kategorie des Wissens.
 * @property {string[]} tags - Associated tags. / Zugehörige Tags.
 * @property {string[]} sourceDocumentIds - IDs of the documents this knowledge was extracted from. / IDs der Dokumente, aus denen dieses Wissen extrahiert wurde.
 * @property {string} createdAt - The ISO 8601 timestamp of creation. / Der ISO 8601 Zeitstempel der Erstellung.
 */
export interface KnowledgeItem {
    id: string;
    title: string;
    summary: string;
    category: string;
    tags: string[];
    sourceDocumentIds: string[];
    createdAt: string;
}

/**
 * @interface TimelineEvent
 * @description Represents a single event on the case timeline.
 * @description Stellt ein einzelnes Ereignis auf der Zeitleiste des Falles dar.
 * @property {string} id - Unique identifier for the event. / Eindeutiger Bezeichner für das Ereignis.
 * @property {string} date - The date of the event (can be imprecise, e.g., 'Mid-2023'). / Das Datum des Ereignisses (kann ungenau sein, z.B. 'Mitte 2023').
 * @property {string} title - The title of the event. / Der Titel des Ereignisses.
 * @property {string} description - A description of the event. / Eine Beschreibung des Ereignisses.
 * @property {string[]} documentIds - IDs of related documents. / IDs der zugehörigen Dokumente.
 */
export interface TimelineEvent {
    id: string;
    date: string;
    title: string;
    description: string;
    documentIds: string[];
}

/**
 * @interface Tag
 * @description Represents a single tag that can be applied to documents or other items.
 * @description Stellt ein einzelnes Tag dar, das auf Dokumente oder andere Elemente angewendet werden kann.
 * @property {string} id - Unique identifier for the tag. / Eindeutiger Bezeichner für das Tag.
 * @property {string} name - The name of the tag. / Der Name des Tags.
 */
export interface Tag {
    id: string;
    name: string;
}

/**
 * @interface DocEntity
 * @description A linking table entry between a document and an entity.
 * @description Ein Verknüpfungstabelleneintrag zwischen einem Dokument und einer Entität.
 * @property {string} docId - The ID of the document. / Die ID des Dokuments.
 * @property {string} entityId - The ID of the entity. / Die ID der Entität.
 */
export interface DocEntity {
    docId: string;
    entityId: string;
}

/**
 * @interface KnowledgeTag
 * @description A linking table entry between a knowledge item and a tag.
 * @description Ein Verknüpfungstabelleneintrag zwischen einem Wissenselement und einem Tag.
 * @property {string} knowledgeId - The ID of the knowledge item. / Die ID des Wissenselements.
 * @property {string} tagId - The ID of the tag. / Die ID des Tags.
 */
export interface KnowledgeTag {
    knowledgeId: string;
    tagId: string;
}

/**
 * @interface Contradiction
 * @description Represents a detected contradiction between two statements from different documents.
 * @description Stellt einen erkannten Widerspruch zwischen zwei Aussagen aus unterschiedlichen Dokumenten dar.
 * @property {string} id - Unique identifier for the contradiction. / Eindeutiger Bezeichner für den Widerspruch.
 * @property {string} statement1 - The first statement. / Die erste Aussage.
 * @property {string} statement2 - The second, contradictory statement. / Die zweite, widersprüchliche Aussage.
 * @property {string} explanation - An explanation of why these statements are contradictory. / Eine Erklärung, warum diese Aussagen widersprüchlich sind.
 * @property {string} source1DocId - The ID of the document containing the first statement. / Die ID des Dokuments, das die erste Aussage enthält.
 * @property {string} source2DocId - The ID of the document containing the second statement. / Die ID des Dokuments, das die zweite Aussage enthält.
 */
export interface Contradiction {
    id: string;
    statement1: string;
    statement2: string;
    explanation: string;
    source1DocId: string;
    source2DocId: string;
}

/**
 * @interface CaseContext
 * @description Stores the overall context of the case.
 * @description Speichert den Gesamtkontext des Falles.
 * @property {number} id - A fixed ID, always 1 for this singleton record. / Eine feste ID, immer 1 für diesen Singleton-Datensatz.
 * @property {string} caseDescription - The user-provided description of the case. / Die vom Benutzer bereitgestellte Beschreibung des Falles.
 * @property {Risks} risks - The identified risks in the case. / Die im Fall identifizierten Risiken.
 * @property {string} mitigationStrategies - Strategies to mitigate the identified risks. / Strategien zur Minderung der identifizierten Risiken.
 */
export interface CaseContext {
    id: number; // Always 1 for single record
    caseDescription: string;
    risks: Risks;
    mitigationStrategies: string;
}

/**
 * @interface Task
 * @description Represents a single task or to-do item.
 * @description Stellt eine einzelne Aufgabe oder ein To-Do-Element dar.
 * @property {string} id - Unique identifier for the task. / Eindeutiger Bezeichner für die Aufgabe.
 * @property {string} text - The description of the task. / Die Beschreibung der Aufgabe.
 * @property {boolean} isCompleted - Whether the task has been completed. / Ob die Aufgabe erledigt ist.
 * @property {'hoch' | 'mittel' | 'niedrig'} urgency - The urgency of the task. / Die Dringlichkeit der Aufgabe.
 * @property {string} source - Where the task originated from (e.g., 'AI suggestion', 'user created'). / Woher die Aufgabe stammt (z.B. 'KI-Vorschlag', 'Benutzer erstellt').
 * @property {string} createdAt - The ISO 8601 timestamp of creation. / Der ISO 8601 Zeitstempel der Erstellung.
 */
export interface Task {
    id: string;
    text: string;
    isCompleted: boolean;
    urgency: 'hoch' | 'mittel' | 'niedrig';
    source: string;
    createdAt: string;
}

// --- UI & State-related (Non-DB) Types ---

/**
 * @interface DocumentAnalysis
 * @description Holds the results of a preliminary analysis of a single document.
 * @description Enthält die Ergebnisse einer vorläufigen Analyse eines einzelnen Dokuments.
 * @property {'hoch' | 'mittel' | 'niedrig'} complexity - The assessed complexity of the document. / Die eingeschätzte Komplexität des Dokuments.
 * @property {string} complexityJustification - The reason for the complexity assessment. / Die Begründung für die Komplexitätseinschätzung.
 * @property {object} workloadEstimate - Estimated time in hours for various tasks. / Geschätzter Zeitaufwand in Stunden für verschiedene Aufgaben.
 * @property {object} costEstimate - Cost estimation based on German standards (RVG/JVEG). / Kostenschätzung basierend auf deutschen Standards (RVG/JVEG).
 * @property {string} documentType - The identified type of the document (e.g., 'Police Report'). / Der identifizierte Typ des Dokuments (z.B. 'Polizeibericht').
 * @property {object[]} recommendations - Recommended actions based on the analysis. / Empfohlene Maßnahmen basierend auf der Analyse.
 * @property {string[]} [suggestedActions] - Optional list of suggested next steps. / Optionale Liste von vorgeschlagenen nächsten Schritten.
 */
export interface DocumentAnalysis {
    complexity: 'hoch' | 'mittel' | 'niedrig';
    complexityJustification: string;
    workloadEstimate: {
        research: number;
        classification: number;
        analysis: number;
        documentation: number;
        correspondence: number;
        followUp: number;
        total: number;
    };
    costEstimate: {
        rvgBased: number;
        jvegBased: number;
        recommended: number;
    };
    documentType: string;
    recommendations: {
        category: string;
        urgency: 'hoch' | 'mittel' | 'niedrig';
        text: string;
    }[];
    suggestedActions?: string[];
}

/**
 * @interface DocumentAnalysisResults
 * @description A dictionary mapping document IDs to their analysis results.
 * @description Ein Wörterbuch, das Dokumenten-IDs ihren Analyseergebnissen zuordnet.
 */
export interface DocumentAnalysisResults {
    [docId: string]: DocumentAnalysis;
}

/**
 * @interface DetailedAnalysis
 * @description Holds the results of a deep, content-focused analysis of a document.
 * @description Enthält die Ergebnisse einer tiefen, inhaltsorientierten Analyse eines Dokuments.
 */
export interface DetailedAnalysis {
    beteiligte_parteien: {
        name: string;
        type: 'Person' | 'Organisation' | 'Standort' | 'Unbekannt';
        description: string;
    }[];
    rechtliche_grundlagen: {
        reference: string;
        description: string;
    }[];
    zentrale_fakten: string[];
    menschenrechtliche_implikationen: string[];
    schlüsselwörter: string[];
    sentiment: 'positiv' | 'negativ' | 'neutral';
    suggestedActions: string[];
    erkannte_ereignisse?: {
        datum: string;
        titel: string;
        beschreibung: string;
    }[];
    correspondenceAnalysis?: {
        findings: string[];
        intent: string;
        riskAssessment: string;
    };
}

/**
 * @interface DetailedAnalysisResults
 * @description A dictionary mapping document IDs to their detailed analysis results.
 * @description Ein Wörterbuch, das Dokumenten-IDs ihren detaillierten Analyseergebnissen zuordnet.
 */
export interface DetailedAnalysisResults {
    [docId: string]: DetailedAnalysis;
}

/**
 * @interface AgentActivity
 * @description Logs an action performed by an AI agent.
 * @description Protokolliert eine von einem KI-Agenten durchgeführte Aktion.
 * @property {string} id - Unique ID for the log entry. / Eindeutige ID für den Protokolleintrag.
 * @property {string} timestamp - The ISO 8601 timestamp of the activity. / Der ISO 8601 Zeitstempel der Aktivität.
 * @property {string} agentName - The name of the agent that performed the action. / Der Name des Agenten, der die Aktion ausgeführt hat.
 * @property {string} action - A description of the action performed. / Eine Beschreibung der durchgeführten Aktion.
 * @property {'erfolg' | 'fehler'} result - The result of the action. / Das Ergebnis der Aktion.
 */
export interface AgentActivity {
    id: string;
    timestamp: string;
    agentName: string;
    action: string;
    result: 'erfolg' | 'fehler';
}

/**
 * @interface Risks
 * @description A set of boolean flags indicating various types of risks identified in the case.
 * @description Eine Reihe von booleschen Flags, die verschiedene Arten von im Fall identifizierten Risiken anzeigen.
 */
export interface Risks {
    physical: boolean;
    legal: boolean;
    digital: boolean;
    intimidation: boolean;
    evidenceManipulation: boolean;
    secondaryTrauma: boolean;
    burnout: boolean;
    psychologicalBurden: boolean;
}

/**
 * @interface KPI
 * @description Represents a Key Performance Indicator for the case.
 * @description Stellt einen Key Performance Indicator (KPI) für den Fall dar.
 * @property {string} id - Unique identifier for the KPI. / Eindeutiger Bezeichner für den KPI.
 * @property {string} name - The name of the KPI. / Der Name des KPI.
 * @property {string} target - The target value or state for the KPI. / Der Zielwert oder -zustand für den KPI.
 * @property {number} progress - The current progress towards the target (0-100). / Der aktuelle Fortschritt in Richtung des Ziels (0-100).
 */
export interface KPI {
    id: string;
    name: string;
    target: string;
    progress: number;
}

/**
 * @interface Insight
 * @description Represents a single insight, observation, or recommendation generated by the system.
 * @description Stellt eine einzelne Erkenntnis, Beobachtung oder Empfehlung dar, die vom System generiert wurde.
 * @property {string} id - Unique identifier for the insight. / Eindeutiger Bezeichner für die Erkenntnis.
 * @property {string} text - The content of the insight. / Der Inhalt der Erkenntnis.
 * @property {string} source - The origin of the insight (e.g., 'Legal Expert Agent'). / Die Herkunft der Erkenntnis (z.B. 'Legal Expert Agent').
 * @property {'observation' | 'recommendation' | 'risk'} type - The type of the insight. / Der Typ der Erkenntnis.
 */
export interface Insight {
    id: string;
    text: string;
    source: string;
    type: 'observation' | 'recommendation' | 'risk';
}

/**
 * @interface ChecklistItem
 * @description Represents a single item in a checklist, for example, for dispatching a case.
 * @description Stellt ein einzelnes Element in einer Checkliste dar, zum Beispiel für den Versand eines Falles.
 * @property {string} id - Unique identifier for the checklist item. / Eindeutiger Bezeichner für das Checklisten-Element.
 * @property {string} text - The text of the checklist item. / Der Text des Checklisten-Elements.
 * @property {boolean} checked - Whether the item has been checked off. / Ob das Element abgehakt wurde.
 */
export interface ChecklistItem {
    id: string;
    text: string;
    checked: boolean;
}

/**
 * @interface EntityRelationship
 * @description Defines a relationship between one entity and another.
 * @description Definiert eine Beziehung zwischen einer Entität und einer anderen.
 * @property {string} targetEntityId - The ID of the entity this relationship points to. / Die ID der Entität, auf die diese Beziehung verweist.
 * @property {string} targetEntityName - The name of the target entity. / Der Name der Zielentität.
 * @property {string} description - A description of the relationship (e.g., 'works for', 'is the mother of'). / Eine Beschreibung der Beziehung (z.B. 'arbeitet für', 'ist die Mutter von').
 */
export interface EntityRelationship {
    targetEntityId: string;
    targetEntityName: string;
    description: string;
}

/**
 * @interface CaseEntity
 * @description Extends the base Entity type with UI-specific properties like relationships and document links.
 * @description Erweitert den Basis-Entitätstyp um UI-spezifische Eigenschaften wie Beziehungen und Dokumentenverknüpfungen.
 * @property {EntityRelationship[]} [relationships] - A list of relationships this entity has with others. / Eine Liste von Beziehungen, die diese Entität zu anderen hat.
 * @property {string[]} [documentIds] - A list of document IDs where this entity is mentioned. / Eine Liste von Dokument-IDs, in denen diese Entität erwähnt wird.
 */
export interface CaseEntity extends Entity {
    relationships?: EntityRelationship[];
    documentIds?: string[];
}

/**
 * @interface DocumentLink
 * @description Represents a link (relationship) between two documents.
 * @description Stellt eine Verknüpfung (Beziehung) zwischen zwei Dokumenten dar.
 * @property {string} id - Unique ID for the link. / Eindeutige ID für die Verknüpfung.
 * @property {string} sourceDocId - The ID of the source document. / Die ID des Quelldokuments.
 * @property {string} targetDocId - The ID of the target document. / Die ID des Zieldokuments.
 * @property {string} description - A description of why the documents are linked. / Eine Beschreibung, warum die Dokumente verknüpft sind.
 * @property {'explicit' | 'suggested'} type - The type of link (user-created or AI-suggested). / Der Typ der Verknüpfung (benutzererstellt oder KI-vorgeschlagen).
 */
export interface DocumentLink {
  id: string;
  sourceDocId: string;
  targetDocId: string;
  description: string;
  type: 'explicit' | 'suggested';
}

/**
 * @interface SuggestedLink
 * @description Extends a DocumentLink with a reason for the AI's suggestion.
 * @description Erweitert einen DocumentLink um eine Begründung für den Vorschlag der KI.
 * @property {string} reason - The justification for suggesting the link. / Die Begründung für den Vorschlag der Verknüpfung.
 */
export interface SuggestedLink extends DocumentLink {
    reason: string;
}

/**
 * @interface SuggestedEntity
 * @description Represents an entity that has been suggested by the AI but not yet confirmed by the user.
 * @description Stellt eine Entität dar, die von der KI vorgeschlagen, aber noch nicht vom Benutzer bestätigt wurde.
 * @property {string} id - Unique identifier for the suggested entity. / Eindeutiger Bezeichner für die vorgeschlagene Entität.
 * @property {string} name - The name of the suggested entity. / Der Name der vorgeschlagenen Entität.
 * @property {string} type - The type of the suggested entity. / Der Typ der vorgeschlagenen Entität.
 * @property {string} description - The description of the suggested entity. / Die Beschreibung der vorgeschlagenen Entität.
 * @property {string} sourceDocumentId - The ID of the document where the entity was found. / Die ID des Dokuments, in dem die Entität gefunden wurde.
 * @property {string} sourceDocumentName - The name of the source document. / Der Name des Quelldokuments.
 */
export interface SuggestedEntity {
    id: string;
    name: string;
    type: string;
    description: string;
    sourceDocumentId: string;
    sourceDocumentName: string;
}

/**
 * @interface UNSubmission
 * @description Represents a submission to a UN body.
 * @description Stellt eine Einreichung bei einem UN-Gremium dar.
 * @property {string} id - Unique identifier for the submission. / Eindeutiger Bezeichner für die Einreichung.
 * @property {string} title - The title of the submission. / Der Titel der Einreichung.
 * @property {'draft' | 'submitted'} status - The current status of the submission. / Der aktuelle Status der Einreichung.
 * @property {{ [section: string]: string }} content - The content of the submission, organized by sections. / Der Inhalt der Einreichung, nach Abschnitten geordnet.
 */
export interface UNSubmission {
    id: string;
    title: string;
    status: 'draft' | 'submitted';
    content: { [section: string]: string };
}

/**
 * @interface EthicsAnalysis
 * @description Holds the results of an ethical analysis of the case.
 * @description Enthält die Ergebnisse einer ethischen Analyse des Falles.
 * @property {string} biasAssessment - An assessment of potential biases in the case data or analysis. / Eine Bewertung potenzieller Voreingenommenheiten in den Falldaten oder der Analyse.
 * @property {string[]} privacyConcerns - A list of identified privacy concerns. / Eine Liste identifizierter Datenschutzbedenken.
 * @property {string[]} recommendations - Recommendations for addressing ethical issues. / Empfehlungen zum Umgang mit ethischen Fragen.
 */
export interface EthicsAnalysis {
    biasAssessment: string;
    privacyConcerns: string[];
    recommendations: string[];
}

/**
 * @interface CaseSummary
 * @description A summary of the entire case, generated by the AI.
 * @description Eine Zusammenfassung des gesamten Falles, generiert von der KI.
 * @property {string} summary - The main summary text. / Der Hauptzusammenfassungstext.
 * @property {object[]} identifiedRisks - A list of identified risks with descriptions. / Eine Liste identifizierter Risiken mit Beschreibungen.
 * @property {object[]} suggestedNextSteps - A list of suggested next steps with justifications. / Eine Liste vorgeschlagener nächster Schritte mit Begründungen.
 * @property {string} generatedAt - The ISO 8601 timestamp of when the summary was generated. / Der ISO 8601 Zeitstempel, wann die Zusammenfassung generiert wurde.
 */
export interface CaseSummary {
    summary: string;
    identifiedRisks: { risk: string; description: string; }[];
    suggestedNextSteps: { step: string; justification: string; }[];
    generatedAt: string;
}

/**
 * @interface AnalysisChatMessage
 * @description Represents a single message in a chat with an analysis agent.
 * @description Stellt eine einzelne Nachricht in einem Chat mit einem Analyse-Agenten dar.
 * @property {'user' | 'model'} role - The role of the message sender. / Die Rolle des Nachrichtenabsenders.
 * @property {string} text - The content of the message. / Der Inhalt der Nachricht.
 */
export interface AnalysisChatMessage {
    role: 'user' | 'model';
    text: string;
}

/**
 * @interface AISettings
 * @description Defines settings for the generative AI model.
 * @description Definiert Einstellungen für das generative KI-Modell.
 * @property {number} temperature - Controls the randomness of the output. / Steuert die Zufälligkeit der Ausgabe.
 * @property {number} topP - The nucleus sampling parameter. / Der Nucleus-Sampling-Parameter.
 */
export interface AISettings {
    temperature: number;
    topP: number;
}

/**
 * @interface ComplexitySettings
 * @description Defines the thresholds for complexity assessment.
 * @description Definiert die Schwellenwerte für die Komplexitätsbewertung.
 * @property {number} low - The threshold for 'low' complexity. / Der Schwellenwert für 'niedrige' Komplexität.
 * @property {number} medium - The threshold for 'medium' complexity. / Der Schwellenwert für 'mittlere' Komplexität.
 */
export interface ComplexitySettings {
    low: number;
    medium: number;
}

/**
 * @interface AppSettings
 * @description A container for all application settings.
 * @description Ein Container für alle Anwendungseinstellungen.
 * @property {AISettings} ai - Settings for the AI model. / Einstellungen für das KI-Modell.
 * @property {ComplexitySettings} complexity - Settings for complexity assessment. / Einstellungen für die Komplexitätsbewertung.
 */
export interface AppSettings {
    ai: AISettings;
    complexity: ComplexitySettings;
}

/**
 * @interface AuditLogEntry
 * @description Represents a single entry in the audit log.
 * @description Stellt einen einzelnen Eintrag im Audit-Protokoll dar.
 * @property {string} id - Unique identifier for the log entry. / Eindeutiger Bezeichner für den Protokolleintrag.
 * @property {string} timestamp - The ISO 8601 timestamp of the event. / Der ISO 8601 Zeitstempel des Ereignisses.
 * @property {string} action - A description of the action that was performed. / Eine Beschreibung der durchgeführten Aktion.
 * @property {string} details - Additional details about the action. / Zusätzliche Details zur Aktion.
 */
export interface AuditLogEntry {
    id: string;
    timestamp: string;
    action: string;
    details: string;
}

/**
 * @interface AppState
 * @description Represents the entire state of the application.
 * @description Repräsentiert den gesamten Zustand der Anwendung.
 */
export interface AppState {
    documents: Document[];
    documentAnalysisResults: DocumentAnalysisResults;
    detailedAnalysisResults: DetailedAnalysisResults;
    generatedDocuments: GeneratedDocument[];
    caseDescription: string;
    agentActivityLog: AgentActivity[];
    risks: Risks;
    mitigationStrategies: string;
    kpis: KPI[];
    timelineEvents: TimelineEvent[];
    insights: Insight[];
    pinnedInsights: Insight[];
    dispatchDocument: GeneratedDocument | null;
    dispatchCoverLetter: string;
    dispatchChecklist: ChecklistItem[];
    caseEntities: CaseEntity[];
    suggestedEntities: SuggestedEntity[];
    knowledgeItems: KnowledgeItem[];
    contradictions: Contradiction[];
    documentLinks: DocumentLink[];
    suggestedLinks: SuggestedLink[];
    unSubmissions: UNSubmission[];
    ethicsAnalysis: EthicsAnalysis | null;
    caseSummary: CaseSummary | null;
    settings: AppSettings;
    tags: Tag[];
    auditLog: AuditLogEntry[];
}